## Run this first

In [1]:
import numpy as np
%config IPCompleter.greedy=True

### Comparing with list,sets and tuple etc.

In [10]:
%%time
N = 100000000
list_ = list(range(N))
for i in range(N):
    list_[i] = list_[i]*list_[i]

Wall time: 16.1 s


In [9]:
%%time
list_ = list(range(N))
list_ = [item*item for item in list_]

Wall time: 10.8 s


In [11]:
%%time
list_ = list(range(N))
list_ = map(lambda x:x*x,list_)

Wall time: 2.82 s


In [12]:
%%time
list_ = list(range(N))
list_sum = 0
for item in list_:
    list_sum+=item

Wall time: 22 s


In [13]:
%%time
list_ = list(range(N))
list_sum = sum(list_)

Wall time: 6.26 s


## Numpy

### Intro

In [9]:
%%time
N = 100000000
arr = np.arange(N)
arr = arr*arr

Wall time: 245 ms


In [11]:
%%time
arr = np.arange(N)
arr_sum = np.sum(arr)

Wall time: 139 ms


In [46]:
N = 27
arr = np.arange(N).reshape(3,3,3)
print(arr,type(arr))
print("\n")
print(arr[0,1:3,:])

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]] <class 'numpy.ndarray'>


[[3 4 5]
 [6 7 8]]


In [52]:
arr = np.array([1,2,3,4,5,6],dtype='int64')
print(arr)

[1 2 3 4 5 6]


In [57]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)

int64
1
(6,)
6
8


In [62]:
arr = np.array([0.1,2,3,4,5,6])
print(arr)

[0.1 2.  3.  4.  5.  6. ]


In [72]:
print(arr.dtype)
print(arr.ndim)
print(arr.shape)
print(arr.size)
print(arr.itemsize)

int32
2
(2, 3)
6
4


In [79]:
arr2d = np.array([
    [1,2,3],
    [4,5,6]
])
print(arr2d.dtype)
print(arr2d.ndim)
print(arr2d.shape)
print(arr2d.size)
print(arr2d.itemsize)

int32
2
(2, 3)
6
4


In [83]:
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(arr3d.dtype)
print(arr3d.ndim)
print(arr3d.shape)
print(arr3d.size)
print(arr3d.itemsize)

int32
3
(2, 2, 3)
12
4


In [89]:
# Tuple should be given for ones function in np
print(np.ones((3,3,3)))
1729*np.ones((3,3,3))

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


array([[[1729., 1729., 1729.],
        [1729., 1729., 1729.],
        [1729., 1729., 1729.]],

       [[1729., 1729., 1729.],
        [1729., 1729., 1729.],
        [1729., 1729., 1729.]],

       [[1729., 1729., 1729.],
        [1729., 1729., 1729.],
        [1729., 1729., 1729.]]])

In [91]:
print(np.zeros((2,3,4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [131]:
# Provides random number within given number
print(np.random.randint(10))
# range of numbers and shape of array
print(np.random.randint(0,100,(3,3)))
# Will give series of number with normal distribution with mean 0 and varince 1 where n denotes normal distribution
print(np.random.randn(2,3))
# Will give numbers unformaly between 0 to 1
print(np.random.rand(2,3))

9
[[ 1 99 33]
 [95 48 22]
 [ 3 22 63]]
[[ 0.08946461 -0.4356366   0.60805174]
 [-0.52327575 -2.590004   -0.13061485]]
[[0.44644715 0.89460033 0.94056868]
 [0.67652531 0.44835078 0.07152934]]


In [143]:
# array within given range with step size
print(
)
# creates linearspace between the extremes
print(np.linspace(1,100,10))

[  0  10  20  30  40  50  60  70  80  90 100]
[  1.  12.  23.  34.  45.  56.  67.  78.  89. 100.]


In [154]:
print(np.array([True,False,False,True,False,True]))
str_arr = np.array(['a','b','c','ddadsd'])
print(str_arr,str_arr.dtype)  # U6 unicode values with length

[ True False False  True False  True]
['a' 'b' 'c' 'ddadsd'] <U6


In [169]:
str_arr1 = np.array(['1.5','1.7','0.8','1.1'],dtype='float32')
print(str_arr1)
str_arr2 = np.array(['1.5','1.7','0.8','1.1'],dtype='int')  # throws error when trying to convert to int as they are floating number
print(str_arr2)

[1.5 1.7 0.8 1.1]


ValueError: invalid literal for int() with base 10: '1.5'

### Indexing

In [178]:
arr3d = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(arr3d[1,0,2])

9


In [199]:
print(arr3d[0,:,:])
print(arr3d[:,1,:])
print(arr3d[:,:,0:2])

[[1 2 3]
 [4 5 6]]
[[ 4  5  6]
 [10 11 12]]
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]


In [206]:
print(arr3d%2 == 0)
print(arr3d[arr3d%2 == 0])
print(arr3d[(arr3d%2 == 1) & (arr3d > 3)])

[[[False  True False]
  [ True False  True]]

 [[False  True False]
  [ True False  True]]]
[ 2  4  6  8 10 12]
[ 5  7  9 11]


In [215]:
arr_slice = arr3d[:,:,0:2]
print(arr_slice)
print(arr_slice.ndim)
print(arr_slice.shape)
arr_slice[0,0,0] = 1729
print(arr_slice)
print(arr3d)  ## arr3d also chnaged the reference is changed / not doing deep copy

[[[1729    2]
  [   4    5]]

 [[   7    8]
  [  10   11]]]
3
(2, 2, 2)
[[[1729    2]
  [   4    5]]

 [[   7    8]
  [  10   11]]]
[[[1729    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]]


In [218]:
arr_slice = np.copy(arr3d[:,:,0:2])
arr_slice[0,0,0] = 1
print(arr_slice)
print(arr3d)

[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]]
[[[1729    2    3]
  [   4    5    6]]

 [[   7    8    9]
  [  10   11   12]]]


In [226]:
arr = np.random.randint(0,10,(5))
print(arr)
my_indices = [1,3,4]
print(arr[my_indices])

[5 7 2 2 6]
[7 2 6]


### Numpy Operations

In [260]:
arr1 = np.random.randn(3,4)
arr2 = np.random.randn(3,4)
print(arr1 + arr2)
print(arr1-arr2)
print(arr1*arr2)
print(arr1/arr2)

[[-0.54801413 -0.43206733  1.08790578  1.44956847]
 [-2.5998601   1.79281401  1.13435786  0.06916318]
 [ 1.6379862  -0.02324247 -0.55023509  0.54674896]]
[[-2.57074622 -0.11698886  0.49839177  0.50593512]
 [ 0.11927339 -1.34962374 -1.23513115 -0.73785084]
 [ 1.97305467  0.6472667   0.18959379  0.79945027]]
[[-1.57710416  0.04324895  0.23378616  0.4613196 ]
 [ 1.6862616   0.34817446 -0.05969531 -0.13491008]
 [-0.30248648 -0.10460349  0.06670321 -0.08504658]]
[[ -1.54185537   1.74260146   2.69085638   2.07231294]
 [  0.91227103   0.14103391  -0.04252955  -0.82859486]
 [-10.77702381  -0.93067219   0.48746584  -5.32723481]]


In [261]:
print(np.exp(arr1))  # e power of value at the index
print(np.log(arr2))
print(np.sin(arr2))
print(np.cos(arr2))
print(np.sqrt(arr2))

[[0.21026636 0.75993065 2.21034536 2.65847273]
 [0.28929934 1.24806598 0.9508617  0.71580762]
 [6.08313651 1.36617125 0.83500242 1.9603041 ]]
[[ 0.01130194         nan -1.22160396 -0.75116477]
 [        nan  0.45185167  0.16952714 -0.90756142]
 [        nan         nan         nan         nan]]
[[ 0.8475576  -0.15688839  0.29050735  0.45450523]
 [-0.97777386  0.99999991  0.9264029   0.39264611]
 [-0.16675162 -0.32900959 -0.36153566 -0.12601474]]
[[ 5.30703413e-01  9.87616339e-01  9.56872761e-01  8.90744071e-01]
 [ 2.09662313e-01 -4.22545630e-04  3.76533755e-01  9.19689639e-01]
 [ 9.85998934e-01  9.44326580e-01  9.32358282e-01  9.92028370e-01]]
[[1.00566697        nan 0.54291529 0.68688913]
 [       nan 1.2534827  1.08845969 0.63522202]
 [       nan        nan        nan        nan]]


C:\Users\malla\anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in log
  
C:\Users\malla\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: invalid value encountered in sqrt
  """


In [262]:
arr_inv = 1/arr1
print(arr_inv)

arr1 = np.zeros((3,5))
arr_inv = 1/arr1
print(arr_inv)  # does not throw error give inf indicating infinite value

[[ -0.64128044  -3.64261439   1.26079751   1.02275445]
 [ -0.80626087   4.51273448 -19.84652716  -2.99093299]
 [  0.55385693   3.20500372  -5.54567644   1.4856642 ]]
[[inf inf inf inf inf]
 [inf inf inf inf inf]
 [inf inf inf inf inf]]


C:\Users\malla\anaconda3\lib\site-packages\ipykernel_launcher.py:5: RuntimeWarning: divide by zero encountered in true_divide
  """


In [263]:
print(np.isinf(arr_inv))

[[ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


### Exercise on finding number of points outside n-dimensional sphere

In [442]:
### Using normal functions
def within(ndim,s):
    less_than = 0
    greater_than = 0
    arr = np.random.rand(s,ndim)
    df0 = np.zeros((s,1))
    for i in range(s):
        for j in range(ndim):
            df0[i] += arr[i][j]**2
        df0[i] = np.sqrt(df0[i])
        if df0[i] <=1:
            less_than+=1
        else:
            greater_than+=1
    print(greater_than/s)

within(2,10000)
within(3,10000)
within(4,10000)
within(5,10000)

0.2132
0.473
0.6922
0.8337


In [443]:
### Using numpy functions
def withinnp(ndim,s):
    greater_than = 0
    arr = np.random.rand(s,ndim)
    print(np.sum(np.sqrt(np.sum(arr*arr,axis=1))>1)/s)

    
for i in range(2,11):
    withinnp(i,100000)

0.21435
0.47447
0.69064
0.83564
0.91986
0.96282
0.98389
0.99309
0.99729


### Broadcasting

In [453]:
arr1 = np.arange(6)
arr1 = arr1.reshape(3,2)
print(arr1)
print(arr1.shape)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [454]:
arr2 = np.arange(6).reshape(3,2)
print(arr2+arr1)

[[ 0  2]
 [ 4  6]
 [ 8 10]]


In [482]:
print(arr2[0].reshape(1,2))
print(arr2)
arr2+arr2[0].reshape(1,2)

[[0 1]]
[[0 1]
 [2 3]
 [4 5]]


array([[0, 2],
       [2, 4],
       [4, 6]])

In [490]:
arr2[:,0].reshape(3,1)+arr2

array([[0, 1],
       [4, 5],
       [8, 9]])

In [495]:
arr1 = np.arange(24).reshape(2,3,4)
arr2 = np.ones((1,4))
arr1+arr2

array([[[ 1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.],
        [ 9., 10., 11., 12.]],

       [[13., 14., 15., 16.],
        [17., 18., 19., 20.],
        [21., 22., 23., 24.]]])

In [496]:
arr1 = np.arange(4)
arr2 = np.arange(5)
arr1+arr2

ValueError: operands could not be broadcast together with shapes (4,) (5,) 

In [498]:
arr1.reshape(4,1)+arr2

array([[0, 1, 2, 3, 4],
       [1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [3, 4, 5, 6, 7]])

In [505]:
# Transpose of array
arr = np.arange(24).reshape(2,3,4)
print(arr.T)

[[[ 0 12]
  [ 4 16]
  [ 8 20]]

 [[ 1 13]
  [ 5 17]
  [ 9 21]]

 [[ 2 14]
  [ 6 18]
  [10 22]]

 [[ 3 15]
  [ 7 19]
  [11 23]]]


### File handling

In [520]:
planets_small = np.loadtxt(r"C:\Users\malla\PadhAI/PadhAI-DataScienceFoundation-Practice/Restart/Week 8/planets_small-200320-181217.txt")

ValueError: could not convert string to float: 'MERCURY'

In [528]:
planets_small = np.loadtxt(r"C:\Users\malla\PadhAI/PadhAI-DataScienceFoundation-Practice/Restart/Week 8/planets_small-200320-181217.txt",skiprows=1)

ValueError: could not convert string to float: 'Mass'

In [545]:
# By default delimitter is space
# It gives nan for the values it does not able to convert & this function is not strict
planets_small = np.loadtxt(r"C:\Users\malla\PadhAI/PadhAI-DataScienceFoundation-Practice/Restart/Week 8/planets_small-200320-181217.txt",
                           skiprows=1,usecols=(1,2,3,4,5,6,7,8,9))

In [546]:
print(planets_small)
print(planets_small.shape)

[[3.3000e-01 4.8700e+00 5.9700e+00 6.4200e-01 1.8980e+03 5.6800e+02
  8.6800e+01 1.0200e+02 1.4600e-02]
 [5.7900e+01 1.0820e+02 1.4960e+02 2.2790e+02 7.7860e+02 1.4335e+03
  2.8725e+03 4.4951e+03 5.9064e+03]
 [4.2226e+03 2.8020e+03 2.4000e+01 2.4700e+01 9.9000e+00 1.0700e+01
  1.7200e+01 1.6100e+01 1.5330e+02]]
(3, 9)


In [547]:
planets = np.loadtxt(r"C:\Users\malla\PadhAI/PadhAI-DataScienceFoundation-Practice/Restart/Week 8/planets-200320-181217.txt",
                           skiprows=1,usecols=(1,2,3,4,5,6,7,8,9))

ValueError: could not convert string to float: 'Unknown'

In [550]:
# It gives nan for the values it does not able to convert & this function is not strict
planets = np.genfromtxt(r"C:\Users\malla\PadhAI/PadhAI-DataScienceFoundation-Practice/Restart/Week 8/planets-200320-181217.txt",
                        skip_header=1,usecols=(1,2,3,4,5,6,7,8,9))
print(planets)
print(planets.shape)

[[ 3.30000e-01  4.87000e+00  5.97000e+00  7.30000e-02  6.42000e-01
   1.89800e+03  5.68000e+02  8.68000e+01  1.02000e+02]
 [ 4.87900e+03  1.21040e+04  1.27560e+04  3.47500e+03  6.79200e+03
   1.42984e+05  1.20536e+05  5.11180e+04  4.95280e+04]
 [ 5.42700e+03  5.24300e+03  5.51400e+03  3.34000e+03  3.93300e+03
   1.32600e+03  6.87000e+02  1.27100e+03  1.63800e+03]
 [ 3.70000e+00  8.90000e+00  9.80000e+00  1.60000e+00  3.70000e+00
   2.31000e+01  9.00000e+00  8.70000e+00  1.10000e+01]
 [ 4.30000e+00  1.04000e+01  1.12000e+01  2.40000e+00  5.00000e+00
   5.95000e+01  3.55000e+01  2.13000e+01  2.35000e+01]
 [ 1.40760e+03 -5.83250e+03  2.39000e+01  6.55700e+02  2.46000e+01
   9.90000e+00  1.07000e+01 -1.72000e+01  1.61000e+01]
 [ 4.22260e+03  2.80200e+03  2.40000e+01  7.08700e+02  2.47000e+01
   9.90000e+00  1.07000e+01  1.72000e+01  1.61000e+01]
 [ 5.79000e+01  1.08200e+02  1.49600e+02  3.84000e-01  2.27900e+02
   7.78600e+02  1.43350e+03  2.87250e+03  4.49510e+03]
 [ 4.60000e+01  1.07500e

In [551]:
np.isnan(planets)

array([[False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, 

In [560]:
planets_new = np.nan_to_num(planets,nan=-1)
#for saving human readable format
np.savetxt("planets_new1.txt",planets_new,delimiter=',')
# for numpy to efficiently process & file size is reduced compared to savetxt function
np.save("planets_new2",planets_new)

In [571]:
%ls

 Volume in drive C is Acer
 Volume Serial Number is 28D9-00DE

 Directory of C:\Users\malla\PadhAI\PadhAI-DataScienceFoundation-Practice\Restart\Week 8

03-10-2021  16:16    <DIR>          .
03-10-2021  16:16    <DIR>          ..
03-10-2021  16:14    <DIR>          .ipynb_checkpoints
28-09-2021  17:03             2,952 cric_data-200320-181217.tsv
28-09-2021  17:03           151,185 FDS_W08_Lecture_NB-200320-184141.ipynb
28-09-2021  17:03            52,175 FDS_W08_Solutions-200320-184141.ipynb
03-10-2021  16:16            52,476 Numpy.ipynb
28-09-2021  17:03            22,551 Numpy_Assignment_Solutions-200320-184846.ipynb
28-09-2021  17:03             3,061 Numpy_Assignments_Questions-200320-184846.ipynb
03-10-2021  16:15             4,532 planets_new1.txt
03-10-2021  16:15             1,568 planets_new2.npy
28-09-2021  17:03               254 planets_small-200320-181217.txt
28-09-2021  17:03             1,436 planets-200320-181217.txt
              10 File(s)        292,190 bytes
     

In [573]:
arr1 = np.random.rand(1000,10)
arr2 = np.random.rand(2000,5)
arr3 = np.random.rand(20,10000)

In [574]:
np.savez("many_arrs",arr1,arr2,arr3)

In [575]:
%ls

 Volume in drive C is Acer
 Volume Serial Number is 28D9-00DE

 Directory of C:\Users\malla\PadhAI\PadhAI-DataScienceFoundation-Practice\Restart\Week 8

03-10-2021  16:20    <DIR>          .
03-10-2021  16:20    <DIR>          ..
03-10-2021  16:14    <DIR>          .ipynb_checkpoints
28-09-2021  17:03             2,952 cric_data-200320-181217.tsv
28-09-2021  17:03           151,185 FDS_W08_Lecture_NB-200320-184141.ipynb
28-09-2021  17:03            52,175 FDS_W08_Solutions-200320-184141.ipynb
03-10-2021  16:20         1,760,748 many_arrs.npz
03-10-2021  16:18            53,987 Numpy.ipynb
28-09-2021  17:03            22,551 Numpy_Assignment_Solutions-200320-184846.ipynb
28-09-2021  17:03             3,061 Numpy_Assignments_Questions-200320-184846.ipynb
03-10-2021  16:15             4,532 planets_new1.txt
03-10-2021  16:15             1,568 planets_new2.npy
28-09-2021  17:03               254 planets_small-200320-181217.txt
28-09-2021  17:03             1,436 planets-200320-181217.txt
 

In [582]:
# for loading the arrays
arr = np.load('many_arrs.npz')
print(arr)
print(type(arr))
print(arr.files)
print(arr['arr_0'])
print(arr['arr_0'].shape)

<class 'numpy.lib.npyio.NpzFile'>
['arr_0', 'arr_1', 'arr_2']
[[0.08718229 0.8798122  0.02892271 ... 0.6101984  0.34747563 0.11950025]
 [0.51504931 0.88570102 0.73214746 ... 0.32220558 0.7335047  0.93596411]
 [0.85869828 0.93511592 0.62286815 ... 0.92376457 0.50911512 0.2533025 ]
 ...
 [0.29069001 0.11902293 0.67708541 ... 0.02995699 0.7262268  0.48910495]
 [0.48717254 0.64995537 0.54232998 ... 0.41850761 0.06253535 0.35209638]
 [0.83086847 0.83221439 0.08625055 ... 0.15189314 0.61672644 0.46537234]]
(1000, 10)


In [583]:
np.savez_compressed('many_arrs_compressed',arr1,arr2,arr3)

In [584]:
%ls

 Volume in drive C is Acer
 Volume Serial Number is 28D9-00DE

 Directory of C:\Users\malla\PadhAI\PadhAI-DataScienceFoundation-Practice\Restart\Week 8

03-10-2021  16:22    <DIR>          .
03-10-2021  16:22    <DIR>          ..
03-10-2021  16:14    <DIR>          .ipynb_checkpoints
28-09-2021  17:03             2,952 cric_data-200320-181217.tsv
28-09-2021  17:03           151,185 FDS_W08_Lecture_NB-200320-184141.ipynb
28-09-2021  17:03            52,175 FDS_W08_Solutions-200320-184141.ipynb
03-10-2021  16:20         1,760,748 many_arrs.npz
03-10-2021  16:22         1,660,219 many_arrs_compressed.npz
03-10-2021  16:22            57,186 Numpy.ipynb
28-09-2021  17:03            22,551 Numpy_Assignment_Solutions-200320-184846.ipynb
28-09-2021  17:03             3,061 Numpy_Assignments_Questions-200320-184846.ipynb
03-10-2021  16:15             4,532 planets_new1.txt
03-10-2021  16:15             1,568 planets_new2.npy
28-09-2021  17:03               254 planets_small-200320-181217.txt
28

In [589]:
np.savez('zeros',np.zeros((10000,10000)))
#
np.savez_compressed('zeros_compressed',np.zeros((10000,10000)))

In [590]:
%ls

 Volume in drive C is Acer
 Volume Serial Number is 28D9-00DE

 Directory of C:\Users\malla\PadhAI\PadhAI-DataScienceFoundation-Practice\Restart\Week 8

03-10-2021  16:25    <DIR>          .
03-10-2021  16:25    <DIR>          ..
03-10-2021  16:14    <DIR>          .ipynb_checkpoints
28-09-2021  17:03             2,952 cric_data-200320-181217.tsv
28-09-2021  17:03           151,185 FDS_W08_Lecture_NB-200320-184141.ipynb
28-09-2021  17:03            52,175 FDS_W08_Solutions-200320-184141.ipynb
03-10-2021  16:20         1,760,748 many_arrs.npz
03-10-2021  16:22         1,660,219 many_arrs_compressed.npz
03-10-2021  16:24            60,742 Numpy.ipynb
28-09-2021  17:03            22,551 Numpy_Assignment_Solutions-200320-184846.ipynb
28-09-2021  17:03             3,061 Numpy_Assignments_Questions-200320-184846.ipynb
03-10-2021  16:15             4,532 planets_new1.txt
03-10-2021  16:15             1,568 planets_new2.npy
28-09-2021  17:03               254 planets_small-200320-181217.txt
28

### Stats with Numpy

In [4]:
arr = np.random.rand(100000,)
print(arr.min())
print(np.amin(arr))
print(arr.max())
print(np.amax(arr))
print(arr.mean())
print(np.mean(arr))
print(arr.var())
print(np.var(arr))
print(arr.std())
print(np.std(arr))
print(np.median(arr))

3.4725032070914708e-06
3.4725032070914708e-06
0.9999921186615616
0.9999921186615616
0.501020570589029
0.501020570589029
0.08333923464275346
0.08333923464275346
0.28868535578160776
0.28868535578160776
0.5010394537452707


In [5]:
print(np.percentile(arr,25)) # 25th percentile
print(np.percentile(arr,50)) # 50th percentile or mdeian

0.25096572841918685
0.5010394537452707


In [6]:
%%time
iqr = np.percentile(arr,75) - np.percentile(arr,25)
print(iqr)

0.49972124440851684
Wall time: 3 ms


In [7]:
%%time
quartiles = np.percentile(arr,[25,75])
iqr = quartiles[1] - quartiles[0]
print(iqr)

0.49972124440851684
Wall time: 2.99 ms


#### Z-Score
##### x = x_mean + z*std(x)

In [16]:
z_score = (arr - np.mean(arr))/np.std(arr)
print(z_score)

[ 1.01105271 -0.60356398 -0.84153597 ...  1.35777692  1.35082234
  0.42212884]


In [18]:
# return 2 arrays - 2nd array gives the bins - 1st array number of points withing the corresponding bins
np.histogram(z_score)

(array([ 9923,  9898, 10106,  9952, 10022,  9969,  9956, 10137,  9887,
        10150], dtype=int64),
 array([-1.73551269, -1.38911873, -1.04272476, -0.6963308 , -0.34993683,
        -0.00354287,  0.34285109,  0.68924506,  1.03563902,  1.38203298,
         1.72842695]))

In [21]:
np.histogram(z_score,bins=5)

(array([19821, 20058, 19991, 20093, 20037], dtype=int64),
 array([-1.73551269, -1.04272476, -0.34993683,  0.34285109,  1.03563902,
         1.72842695]))

In [22]:
np.histogram(z_score,bins = [0,0.25,0.5,0.75,1])

(array([7171, 7287, 7137, 7336], dtype=int64),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))

In [25]:
bins = [0,0.25,0.5,0.75,1]
# this returns a array which contains the numbers which represnets the bin in which they lie in
np.digitize(arr,bins)

array([4, 2, 2, ..., 4, 4, 3], dtype=int64)

In [34]:
arr1 = np.random.randint(0,10,(10))
bins = [0,6,10]
print(np.digitize(arr1,bins))
print(np.digitize(arr1,bins,right=True))

[1 1 2 2 2 2 1 2 1 2]
[0 1 1 2 1 2 1 1 1 2]


In [46]:
arr1 = np.random.randint(50,80,100) # weight
arr2 = np.random.randint(150,180,100) # height
arr3 = np.random.randint(17,22,100) # age

In [47]:
# just concatenates the given arrays
print(np.concatenate((arr1,arr2,arr3)))
print(np.concatenate((arr1,arr2,arr3)).shape)

[ 55  56  68  61  67  62  67  52  69  77  52  51  77  63  56  74  70  52
  68  72  54  69  55  59  69  53  53  62  63  62  57  62  65  68  66  78
  64  60  60  75  56  55  50  74  59  68  78  64  76  67  55  64  52  61
  78  77  54  65  52  79  55  61  61  76  57  58  59  78  56  52  59  61
  71  79  57  79  74  75  63  65  61  50  52  76  75  76  62  68  78  59
  52  67  74  50  51  67  57  59  51  58 174 177 154 170 158 169 159 165
 174 163 170 156 166 169 164 174 151 164 173 159 162 175 175 176 165 174
 166 159 169 179 158 151 152 167 156 168 176 168 178 154 171 168 175 152
 177 169 163 165 160 177 151 157 178 152 176 175 167 156 167 154 167 177
 176 168 166 165 177 152 154 156 165 155 173 150 165 172 167 174 169 177
 162 169 162 175 151 174 162 178 165 162 177 156 161 159 179 151 161 171
 153 153  19  21  17  20  20  20  20  20  18  17  21  17  21  19  19  21
  19  18  20  19  17  17  19  20  17  17  21  17  20  18  20  21  21  20
  19  19  21  20  18  20  20  20  21  20  18  20  2

In [53]:
# add them vertically
arr2d = np.vstack((arr1,arr2,arr3))

In [54]:
# Same as concatenate function 
np.hstack((arr1,arr2,arr3))

array([ 55,  56,  68,  61,  67,  62,  67,  52,  69,  77,  52,  51,  77,
        63,  56,  74,  70,  52,  68,  72,  54,  69,  55,  59,  69,  53,
        53,  62,  63,  62,  57,  62,  65,  68,  66,  78,  64,  60,  60,
        75,  56,  55,  50,  74,  59,  68,  78,  64,  76,  67,  55,  64,
        52,  61,  78,  77,  54,  65,  52,  79,  55,  61,  61,  76,  57,
        58,  59,  78,  56,  52,  59,  61,  71,  79,  57,  79,  74,  75,
        63,  65,  61,  50,  52,  76,  75,  76,  62,  68,  78,  59,  52,
        67,  74,  50,  51,  67,  57,  59,  51,  58, 174, 177, 154, 170,
       158, 169, 159, 165, 174, 163, 170, 156, 166, 169, 164, 174, 151,
       164, 173, 159, 162, 175, 175, 176, 165, 174, 166, 159, 169, 179,
       158, 151, 152, 167, 156, 168, 176, 168, 178, 154, 171, 168, 175,
       152, 177, 169, 163, 165, 160, 177, 151, 157, 178, 152, 176, 175,
       167, 156, 167, 154, 167, 177, 176, 168, 166, 165, 177, 152, 154,
       156, 165, 155, 173, 150, 165, 172, 167, 174, 169, 177, 16

In [58]:
# Given minimum across the columns
print(np.amin(arr2d,axis=1))
print(arr2d.min(axis=1))

[ 50 150  17]
[ 50 150  17]


### Checking stats rules with numpy

#### Mean subtracted array has zero mean

In [90]:
arr = np.random.rand(1000)
arr1 = arr - np.mean(arr)
print(np.mean(arr1)) # Should be zero

# randn - values are normally distributed so mean = 0  and variance = 1
print(np.mean(np.random.randn(1000)))
print(np.var(np.random.randn(1000)))

1.6431300764452316e-17
0.024830602958677006
0.9705244174590378


#### Computing mean with smaller set of values

In [106]:
arr = np.random.rand(100)
for k in range(1,50):
    arr1 = arr[0:k]
    print(k,np.mean(arr1))

1 0.10077318108076838
2 0.19222573868851478
3 0.36884307346521455
4 0.5034865005993545
5 0.5190990919807686
6 0.45101289653257304
7 0.5271307281140503
8 0.5100629094367574
9 0.5020301929933573
10 0.5111318225099908
11 0.479483127208684
12 0.5160827292183426
13 0.5437662961834578
14 0.5085039878891722
15 0.5240875247593048
16 0.5062434269875173
17 0.4969200881926491
18 0.5163164868319117
19 0.5350420461366842
20 0.5293992517868114
21 0.5445787983498546
22 0.5487836023075269
23 0.5490612440992012
24 0.5485249469317052
25 0.5473584203078498
26 0.5554128375994495
27 0.5481200413821044
28 0.531391025426677
29 0.5314055306446569
30 0.5464285245538546
31 0.5311441170713561
32 0.5182856282044148
33 0.5176804074024797
34 0.527729573776937
35 0.5330039548861187
36 0.5336961646957847
37 0.5353589370931652
38 0.5321918797788663
39 0.5233622439008234
40 0.5234895469690176
41 0.5292440422451007
42 0.534532824671364
43 0.538598402708337
44 0.5488164999690681
45 0.5423992622092163
46 0.533863696284089

In [109]:
# Gives mean from 1st number to 1000th number
means = np.cumsum(arr)/np.arange(1,101)
print(means)

[0.10077318 0.19222574 0.36884307 0.5034865  0.51909909 0.4510129
 0.52713073 0.51006291 0.50203019 0.51113182 0.47948313 0.51608273
 0.5437663  0.50850399 0.52408752 0.50624343 0.49692009 0.51631649
 0.53504205 0.52939925 0.5445788  0.5487836  0.54906124 0.54852495
 0.54735842 0.55541284 0.54812004 0.53139103 0.53140553 0.54642852
 0.53114412 0.51828563 0.51768041 0.52772957 0.53300395 0.53369616
 0.53535894 0.53219188 0.52336224 0.52348955 0.52924404 0.53453282
 0.5385984  0.5488165  0.54239926 0.5338637  0.52807102 0.52180178
 0.52850493 0.53609305 0.53095381 0.5344079  0.53792318 0.53875641
 0.54495728 0.54865501 0.55199494 0.54876436 0.54507378 0.54503817
 0.55206221 0.54845217 0.55429664 0.54641044 0.53994322 0.53494295
 0.54171388 0.54497202 0.54352105 0.54592346 0.54537486 0.54506805
 0.54936646 0.55006552 0.5548024  0.55566747 0.55483318 0.5533232
 0.55177041 0.55626571 0.55876647 0.55683953 0.55836892 0.55693509
 0.55761978 0.55551482 0.5522396  0.55225641 0.54626174 0.542895

#### Effect of outliers on mean and median

In [128]:
arr = np.random.randint(1,100,100)
print(np.mean(arr))
print(np.median(arr))

52.44
53.0


In [130]:
arr = np.append(arr,[1000,2000])
print(arr.shape)
print(np.mean(arr))
print(np.median(arr))
# mean has increased and sensitive

(104,)
108.11538461538461
55.5


#### Effect of scaling arrays on mean and median

In [137]:
arr = np.random.rand(100)
print(np.mean(arr))
print(np.median(arr))

0.4646371003776363
0.4874638465263608


In [157]:
arr1 = arr*5 + 7
print(np.mean(arr1))
print(np.median(arr1))
print(np.var(arr1))
print(np.mean(arr1),np.mean(arr)*5+7)
print(np.median(arr1),np.median(arr)*5+7)
print(np.var(arr1),5*5*np.var(arr))
print(np.std(arr1),5*np.std(arr))

9.323185501888183
9.437319232631804
1.9378424075910683
9.323185501888183 9.323185501888181
9.437319232631804 9.437319232631804
1.9378424075910683 1.937842407591069
1.3920640817114234 1.3920640817114236


In [163]:
arr1 = np.random.rand(100)
arr2 = np.random.rand(100)
print(np.mean(0.21*arr1 - 0.75*arr2),0.21*np.mean(arr1) - 0.75*np.mean(arr2))

-0.26056156748337617 -0.26056156748337617


# Case study Cricket

1.   Find mean, median, IQR for Sachin, Rahul, and India

In [95]:
data = np.loadtxt('cric_data-200320-181217.tsv',skiprows=1,usecols=(1,2,3))
sachin = data[:,0]
rahul = data[:,1]
india = data[:,2]
def stats(col):
    mean = np.mean(col)
    median = np.median(col)
    iqr = np.percentile(col,75) - np.percentile(col,25)
    print(f'Mean - {mean}, Median - {median}, IQR - {iqr}')

stats(sachin)
stats(rahul)
stats(india)

print(np.mean(data,axis = 0))
print(np.median(data,axis = 0))
print(np.percentile(data,75,axis = 0) - np.percentile(data,25,axis = 0))

Mean - 39.87555555555556, Median - 27.0, IQR - 57.0
Mean - 32.062222222222225, Median - 22.0, IQR - 46.0
Mean - 220.79555555555555, Median - 216.0, IQR - 98.0
[ 39.87555556  32.06222222 220.79555556]
[ 27.  22. 216.]
[57. 46. 98.]


2.   Find the histogram of Sachin's scores with 10 bins

In [4]:
histogram_sachin = np.histogram(data[:,0],bins=10)
print(histogram_sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1], dtype=int64), array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
       167.4, 186. ]))


3.   Find mean of Sachin's scores grouped by 25 matches

In [57]:
sachin_r = sachin.reshape(9,25)
print(np.mean(sachin_r, axis=1))

[33.96 49.4  38.48 40.16 39.36 38.2  44.6  39.52 35.2 ]


4.   Find mean of Sachin's scores where he has scored a century

In [59]:
sachin = data[:,0]
mean_sachin_century = np.mean(sachin[sachin >= 100])
print(mean_sachin_century)

125.0


5.   Find mean of Sachin's scores when Rahul has scored less than 10

In [60]:
rahul = data[:,1]
mean_sachin_rahul = np.mean(sachin[rahul < 10])
print(mean_sachin_rahul)

40.74285714285714


6.   Find mean for Sachin's scores based on which quartile India's score falls in

In [108]:
qrs = np.percentile(india,[25,50,75,100])
qrs = qrs.reshape(4,1)
index = india < qrs
mean_25 = np.mean(sachin[index[0]])
mean_50 = np.mean(sachin[index[1]])
mean_75 = np.mean(sachin[index[2]])
mean_100 = np.mean(sachin[index[3]])
print(mean_100,mean_75,mean_50,mean_25)

39.799107142857146 31.688622754491018 28.18018018018018 19.672727272727272


7.   For every match find out who has has scored more - Sachin or Rahul

In [131]:
#print(np.where(data[:,0]>data[:,1],'Sachin','Rahul'))

#or
#np.max([1,3,4,5,2]) returns the max value
#np.arg([1,3,4,5,2]) returns the position value
snr = data[:,0:2]
is_rahul_higher = np.argmax(snr,axis=1)
print(np.where(is_rahul_higher == 0,'Sachin','Rahul'))

['Sachin' 'Rahul' 'Rahul' 'Sachin' 'Sachin' 'Rahul' 'Rahul' 'Sachin'
 'Rahul' 'Sachin' 'Rahul' 'Rahul' 'Rahul' 'Sachin' 'Sachin' 'Rahul'
 'Rahul' 'Sachin' 'Rahul' 'Rahul' 'Sachin' 'Rahul' 'Sachin' 'Sachin'
 'Rahul' 'Sachin' 'Sachin' 'Sachin' 'Sachin' 'Sachin' 'Sachin' 'Sachin'
 'Rahul' 'Rahul' 'Sachin' 'Rahul' 'Rahul' 'Sachin' 'Rahul' 'Sachin'
 'Sachin' 'Sachin' 'Sachin' 'Rahul' 'Sachin' 'Rahul' 'Rahul' 'Sachin'
 'Rahul' 'Sachin' 'Rahul' 'Rahul' 'Rahul' 'Rahul' 'Sachin' 'Rahul'
 'Sachin' 'Sachin' 'Rahul' 'Rahul' 'Rahul' 'Sachin' 'Rahul' 'Sachin'
 'Sachin' 'Sachin' 'Sachin' 'Rahul' 'Sachin' 'Rahul' 'Rahul' 'Sachin'
 'Sachin' 'Rahul' 'Rahul' 'Sachin' 'Rahul' 'Rahul' 'Sachin' 'Rahul'
 'Rahul' 'Rahul' 'Rahul' 'Rahul' 'Rahul' 'Sachin' 'Sachin' 'Sachin'
 'Rahul' 'Sachin' 'Sachin' 'Sachin' 'Sachin' 'Sachin' 'Sachin' 'Rahul'
 'Rahul' 'Sachin' 'Rahul' 'Sachin' 'Sachin' 'Rahul' 'Rahul' 'Rahul'
 'Rahul' 'Sachin' 'Rahul' 'Rahul' 'Sachin' 'Sachin' 'Sachin' 'Sachin'
 'Rahul' 'Sachin' 'Rahul' 'Sachin

8.   How many more runs does Sachin score on average after having scored x runs

In [200]:
def sachin_score_x(x):
    sachin = data[:,0]
    return np.mean(sachin[sachin >= x] - x)

print(sachin_score_x(25))
print("\n")

#or

x_arr = np.arange(0,101,5)
x_arr = x_arr.reshape(x_arr.shape[0],1)
indices = sachin >= x_arr
for i in range(x_arr.shape[0]):
    print(x_arr[i],np.mean(sachin[indices[i,:]] - x_arr[i]))

44.10084033613445


[0] 39.87555555555556
[5] 45.61363636363637
[10] 47.48026315789474
[15] 47.45255474452555
[20] 46.824
[25] 44.10084033613445
[30] 45.13461538461539
[35] 43.24742268041237
[40] 44.05882352941177
[45] 43.41558441558441
[50] 43.98529411764706
[55] 42.317460317460316
[60] 38.67213114754098
[65] 37.654545454545456
[70] 37.08163265306123
[75] 34.34782608695652
[80] 30.75
[85] 28.65
[90] 27.4
[95] 26.433333333333334
[100] 25.0


9.   How many matches did Sachin take to score first 1000 runs, next 1000 runs, ...

In [253]:
sachin_cumsum = np.cumsum(sachin)
runs = np.arange(1000,10000,1000)
run = runs.reshape(runs.shape[0],1)
for i in range(run.shape[0]):
    print(f'Sachin took {np.sum(sachin_cumsum <= run[i,:])} matches to score {runs[i]} runs')

Sachin took 29 matches to score 1000 runs
Sachin took 47 matches to score 2000 runs
Sachin took 73 matches to score 3000 runs
Sachin took 98 matches to score 4000 runs
Sachin took 124 matches to score 5000 runs
Sachin took 150 matches to score 6000 runs
Sachin took 173 matches to score 7000 runs
Sachin took 195 matches to score 8000 runs
Sachin took 225 matches to score 9000 runs


In [252]:
np.histogram(sachin_cumsum,bins=np.arange(0,10000,1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30], dtype=int64),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))